# Generated by Django 3.2.9 on 2021-12-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingem', '0003_alter_comment_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
