# Generated by Django 3.2.9 on 2021-12-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Novel',
        ),
    ]
